
services:
  db:
    image: postgres:13
    container_name: football_reservation_db
    environment:
      POSTGRES_DB: football_reservation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD:  admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local